"""Localization for rendered audit reports.

The audit language chosen in the UI controls the *whole* report, not just the
sentences written by the model. Everything the renderer adds itself — section
titles, card labels, badges, risk bands, empty-state sentences, the cover sheet
and the page furniture — is looked up here so a report reads as one document in
one language.

Right-to-left support
---------------------
ReportLab draws glyphs in the order it is given them and performs no Unicode
bidirectional reordering or Arabic glyph shaping. Arabic therefore needs three
things that Latin scripts do not:

1. a font that actually contains Arabic glyphs (the built-in Helvetica does
   not, which is why unshaped Arabic previously rendered as empty boxes);
2. contextual shaping, so letters take their initial/medial/final forms;
3. bidirectional reordering, applied *per rendered line* — reordering a whole
   paragraph and then letting ReportLab wrap it would scramble the line order.

:class:`RtlParagraph` satisfies (3) by wrapping the text itself in logical
order at the width it is given, then shaping each resulting line for display.

Both Arabic dependencies are optional at runtime: if they are unavailable the
text still renders with the correct font and content, only unshaped, rather
than failing the whole download.
"""

from __future__ import annotations

import logging
import re
import threading
from contextvars import ContextVar
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.platypus import Paragraph

logger = logging.getLogger(__name__)

DEFAULT_LANGUAGE = "en"
RTL_LANGUAGES = frozenset({"ar", "fa", "ur", "he"})

# Bundled so the renderer never depends on fonts being installed on the host.
FONT_DIR = Path(__file__).resolve().parent / "assets" / "fonts"
ARABIC_FONT_FILES: Tuple[Tuple[str, str], ...] = (
    ("MizaanArabic", "IBMPlexSansArabic-Regular.ttf"),
    ("MizaanArabic-Bold", "IBMPlexSansArabic-Bold.ttf"),
)

LATIN_FONTS = ("Helvetica", "Helvetica-Bold", "Helvetica-Oblique")

# Arabic, Arabic Supplement/Extended, and the presentation forms produced by
# the reshaper. Used only to decide whether a run needs shaping at all.
_RTL_CHARS = re.compile(
    "[\u0590-\u05FF\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF"
    "\uFB1D-\uFDFF\uFE70-\uFEFF]"
)


# ---------------------------------------------------------------------------
# Catalog
# ---------------------------------------------------------------------------
LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "brand_tagline": "E T H I C A L   ·   T R A N S P A R E N T   ·   S H A R I A H",
        "header_subtitle": "SHARIAH COMPLIANCE AUDIT",
        "footer_left": "Mizaan AI  |  Confidential Report",
        "footer_page": "Page {page} of {total}",
        "footer_right": "Generated by AI  |  {site}",
        "cover_kicker": "AUDIT REPORT",
        "cover_project": "PROJECT NAME",
        "cover_audit_type": "AUDIT TYPE",
        "cover_date": "GENERATED DATE",
        "cover_report_id": "REPORT ID",
        "cover_footer": "Generated by AI  ·  {site}",
        "confidential": "CONFIDENTIAL",
        "doc_title_suffix": "Mizaan AI Audit Report",
        "section_executive_summary": "Executive Summary",
        "section_risk_score": "Risk Score",
        "section_key_findings": "Key Findings",
        "section_compliance": "Compliance Findings",
        "section_risk_factors": "Risk Factors",
        "section_scholarly": "Scholarly Perspectives",
        "section_recommendations": "Actionable Recommendations",
        "section_references": "Qur'an & Hadith References",
        "label_overall_verdict": "OVERALL VERDICT",
        "label_risk_score": "Risk Score",
        "label_confidence": "Confidence",
        "label_classification": "Classification",
        "label_evidence": "EVIDENCE",
        "label_expected_impact": "EXPECTED IMPACT",
        "label_relevance": "RELEVANCE",
        "label_important_notice": "IMPORTANT NOTICE",
        "label_finding": "FINDING {index}",
        "label_risk_exposure": "{band}  ·  SHARIAH RISK EXPOSURE",
        "badge_risk": "RISK: {level}",
        "badge_priority": "{priority} PRIORITY",
        "value_na": "N/A",
        "empty_verdict": "Not stated.",
        "empty_summary": "No executive summary was produced for this audit.",
        "empty_key_findings": "No key findings were highlighted.",
        "empty_indicators": "No compliance indicators were assessed.",
        "empty_finding_text": "No explanation was provided.",
        "empty_recommendations": (
            "No remediation actions were recommended for this audit."
        ),
        "empty_risk_factors": "No structural risk factors were recorded.",
        "empty_scholarly": "No areas of scholarly disagreement were recorded.",
        "empty_references": "No relevant primary references identified.",
        "fallback_category": "Assessment Area",
        "fallback_status": "Requires Review",
        "confidentiality_notice": (
            "This document contains confidential AI-generated Shariah risk "
            "research prepared for the named recipient. It is not a fatwa and "
            "does not constitute financial, legal or investment advice. "
            "Redistribution without written consent is prohibited."
        ),
    },
    "fr": {
        "brand_tagline": "É T H I Q U E   ·   T R A N S P A R E N T   ·   C H A R I A",
        "header_subtitle": "AUDIT DE CONFORMITÉ À LA CHARIA",
        "footer_left": "Mizaan AI  |  Rapport confidentiel",
        "footer_page": "Page {page} sur {total}",
        "footer_right": "Généré par IA  |  {site}",
        "cover_kicker": "RAPPORT D'AUDIT",
        "cover_project": "NOM DU PROJET",
        "cover_audit_type": "TYPE D'AUDIT",
        "cover_date": "DATE DE GÉNÉRATION",
        "cover_report_id": "IDENTIFIANT DU RAPPORT",
        "cover_footer": "Généré par IA  ·  {site}",
        "confidential": "CONFIDENTIEL",
        "doc_title_suffix": "Rapport d'audit Mizaan AI",
        "section_executive_summary": "Résumé exécutif",
        "section_risk_score": "Score de risque",
        "section_key_findings": "Constats clés",
        "section_compliance": "Constats de conformité",
        "section_risk_factors": "Facteurs de risque",
        "section_scholarly": "Points de vue des savants",
        "section_recommendations": "Recommandations concrètes",
        "section_references": "Références du Coran et du Hadith",
        "label_overall_verdict": "VERDICT GLOBAL",
        "label_risk_score": "Score de risque",
        "label_confidence": "Confiance",
        "label_classification": "Classification",
        "label_evidence": "PREUVE",
        "label_expected_impact": "IMPACT ATTENDU",
        "label_relevance": "PERTINENCE",
        "label_important_notice": "AVIS IMPORTANT",
        "label_finding": "CONSTAT {index}",
        "label_risk_exposure": "{band}  ·  EXPOSITION AU RISQUE CHARIA",
        "badge_risk": "RISQUE : {level}",
        "badge_priority": "PRIORITÉ {priority}",
        "value_na": "N/D",
        "empty_verdict": "Non précisé.",
        "empty_summary": "Aucun résumé exécutif n'a été produit pour cet audit.",
        "empty_key_findings": "Aucun constat clé n'a été relevé.",
        "empty_indicators": "Aucun indicateur de conformité n'a été évalué.",
        "empty_finding_text": "Aucune explication n'a été fournie.",
        "empty_recommendations": (
            "Aucune action corrective n'a été recommandée pour cet audit."
        ),
        "empty_risk_factors": "Aucun facteur de risque structurel n'a été enregistré.",
        "empty_scholarly": (
            "Aucun point de divergence entre savants n'a été enregistré."
        ),
        "empty_references": "Aucune référence primaire pertinente n'a été identifiée.",
        "fallback_category": "Domaine évalué",
        "fallback_status": "À examiner",
        "confidentiality_notice": (
            "Ce document contient une recherche confidentielle sur le risque "
            "charia générée par IA, préparée pour le destinataire désigné. Il "
            "ne constitue ni une fatwa ni un conseil financier, juridique ou "
            "en investissement. Toute rediffusion sans consentement écrit est "
            "interdite."
        ),
    },
    "ar": {
        # Arabic is never letter-spaced: inserting spaces between letters would
        # break the cursive joining the shaper depends on.
        "brand_tagline": "أخلاقي  ·  شفّاف  ·  شرعي",
        "header_subtitle": "تدقيق الامتثال الشرعي",
        "footer_left": "ميزان  |  تقرير سري",
        "footer_page": "صفحة {page} من {total}",
        "footer_right": "أُنشئ بالذكاء الاصطناعي  |  {site}",
        "cover_kicker": "تقرير التدقيق",
        "cover_project": "اسم المشروع",
        "cover_audit_type": "نوع التدقيق",
        "cover_date": "تاريخ الإصدار",
        "cover_report_id": "معرّف التقرير",
        "cover_footer": "أُنشئ بالذكاء الاصطناعي  ·  {site}",
        "confidential": "سرّي",
        "doc_title_suffix": "تقرير تدقيق ميزان",
        "section_executive_summary": "الملخص التنفيذي",
        "section_risk_score": "درجة المخاطر",
        "section_key_findings": "أبرز النتائج",
        "section_compliance": "نتائج الامتثال",
        "section_risk_factors": "عوامل المخاطر",
        "section_scholarly": "آراء العلماء",
        "section_recommendations": "توصيات قابلة للتنفيذ",
        "section_references": "مراجع من القرآن والسنة",
        "label_overall_verdict": "الحكم العام",
        "label_risk_score": "درجة المخاطر",
        "label_confidence": "مستوى الثقة",
        "label_classification": "التصنيف",
        "label_evidence": "الدليل",
        "label_expected_impact": "الأثر المتوقع",
        "label_relevance": "وجه الصلة",
        "label_important_notice": "إشعار مهم",
        "label_finding": "النتيجة {index}",
        "label_risk_exposure": "{band}  ·  التعرّض للمخاطر الشرعية",
        "badge_risk": "المخاطر: {level}",
        "badge_priority": "أولوية {priority}",
        "value_na": "غير متاح",
        "empty_verdict": "لم يُذكر.",
        "empty_summary": "لم يُنتج ملخص تنفيذي لهذا التدقيق.",
        "empty_key_findings": "لم يتم إبراز أي نتائج رئيسية.",
        "empty_indicators": "لم يتم تقييم أي مؤشرات امتثال.",
        "empty_finding_text": "لم يُقدَّم أي تفسير.",
        "empty_recommendations": "لم يُوصَ بأي إجراءات تصحيحية لهذا التدقيق.",
        "empty_risk_factors": "لم تُسجَّل أي عوامل مخاطر هيكلية.",
        "empty_scholarly": "لم تُسجَّل أي مواضع خلاف بين العلماء.",
        "empty_references": "لم يتم تحديد مراجع أصلية ذات صلة.",
        "fallback_category": "مجال التقييم",
        "fallback_status": "يتطلب مراجعة",
        "confidentiality_notice": (
            "يحتوي هذا المستند على بحث سري في المخاطر الشرعية أُنشئ بواسطة "
            "الذكاء الاصطناعي وأُعدّ للمستلم المذكور. وهو ليس فتوى ولا يشكل "
            "مشورة مالية أو قانونية أو استثمارية. يُحظر إعادة توزيعه دون "
            "موافقة خطية."
        ),
    },
}

# Section heading glyphs. Latin initials mean nothing in Arabic, so the RTL
# catalog carries its own single-letter marks.
SECTION_ICONS: Dict[str, Dict[str, str]] = {
    "en": {
        "executive_summary": "i", "risk_score": "R", "key_findings": "K",
        "compliance": "F", "risk_factors": "T", "scholarly": "S",
        "recommendations": "A", "references": "Q",
    },
    "ar": {
        "executive_summary": "م", "risk_score": "خ", "key_findings": "ن",
        "compliance": "ا", "risk_factors": "ع", "scholarly": "ف",
        "recommendations": "ت", "references": "ق",
    },
}
SECTION_ICONS["fr"] = SECTION_ICONS["en"]

RISK_BAND_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "LOW": "Low Risk", "MODERATE": "Moderate Risk",
        "ELEVATED": "Elevated Risk", "HIGH": "High Risk",
    },
    "fr": {
        "LOW": "Risque faible", "MODERATE": "Risque modéré",
        "ELEVATED": "Risque élevé", "HIGH": "Risque très élevé",
    },
    "ar": {
        "LOW": "مخاطر منخفضة", "MODERATE": "مخاطر متوسطة",
        "ELEVATED": "مخاطر مرتفعة", "HIGH": "مخاطر عالية جدًا",
    },
}

STATUS_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "COMPLIANT": "COMPLIANT", "CONDITIONAL": "CONDITIONAL",
        "NON_COMPLIANT": "NON-COMPLIANT",
    },
    "fr": {
        "COMPLIANT": "CONFORME", "CONDITIONAL": "CONDITIONNEL",
        "NON_COMPLIANT": "NON CONFORME",
    },
    "ar": {
        "COMPLIANT": "مطابق", "CONDITIONAL": "مشروط",
        "NON_COMPLIANT": "غير مطابق",
    },
}

PRIORITY_LABELS: Dict[str, Dict[str, str]] = {
    "en": {"HIGH": "HIGH", "MEDIUM": "MEDIUM", "LOW": "LOW"},
    "fr": {"HIGH": "HAUTE", "MEDIUM": "MOYENNE", "LOW": "BASSE"},
    "ar": {"HIGH": "عالية", "MEDIUM": "متوسطة", "LOW": "منخفضة"},
}

RISK_LEVEL_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "LOW": "LOW", "MODERATE": "MODERATE", "HIGH": "HIGH",
        "CRITICAL": "CRITICAL",
    },
    "fr": {
        "LOW": "FAIBLE", "MODERATE": "MODÉRÉ", "HIGH": "ÉLEVÉ",
        "CRITICAL": "CRITIQUE",
    },
    "ar": {
        "LOW": "منخفضة", "MODERATE": "متوسطة", "HIGH": "عالية",
        "CRITICAL": "حرجة",
    },
}

# Keyed by the canonical English value so reports stored before the language
# was recorded still translate on re-render.
CLASSIFICATION_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "Shariah Compliant": "Shariah Compliant",
        "Conditionally Compliant": "Conditionally Compliant",
        "Requires Scholar Review": "Requires Scholar Review",
        "Non-Compliant": "Non-Compliant",
    },
    "fr": {
        "Shariah Compliant": "Conforme à la Charia",
        "Conditionally Compliant": "Conforme sous conditions",
        "Requires Scholar Review": "Nécessite l'avis d'un savant",
        "Non-Compliant": "Non conforme",
    },
    "ar": {
        "Shariah Compliant": "متوافق مع الشريعة",
        "Conditionally Compliant": "متوافق بشروط",
        "Requires Scholar Review": "يتطلب مراجعة علمية",
        "Non-Compliant": "غير متوافق",
    },
}

AUDIT_TYPE_LABELS: Dict[str, Dict[str, str]] = {
    "en": {
        "Crypto Protocol Audit": "Crypto Protocol Audit",
        "Business Model Audit": "Business Model Audit",
        "Platform Audit": "Platform Audit",
        "Shariah Compliance Audit": "Shariah Compliance Audit",
    },
    "fr": {
        "Crypto Protocol Audit": "Audit de protocole crypto",
        "Business Model Audit": "Audit du modèle économique",
        "Platform Audit": "Audit de plateforme",
        "Shariah Compliance Audit": "Audit de conformité à la Charia",
    },
    "ar": {
        "Crypto Protocol Audit": "تدقيق بروتوكول العملات الرقمية",
        "Business Model Audit": "تدقيق نموذج الأعمال",
        "Platform Audit": "تدقيق المنصة",
        "Shariah Compliance Audit": "تدقيق الامتثال الشرعي",
    },
}

MONTHS: Dict[str, Tuple[str, ...]] = {
    "en": (
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ),
    "fr": (
        "janvier", "février", "mars", "avril", "mai", "juin",
        "juillet", "août", "septembre", "octobre", "novembre", "décembre",
    ),
    "ar": (
        "يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو",
        "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر",
    ),
}


# Derived from the catalog so adding a language means adding its labels and
# nothing else.
SUPPORTED_LANGUAGES: Tuple[str, ...] = tuple(LABELS)


def normalize_language(value: Any) -> str:
    """Maps any UI/locale value onto a language this renderer supports."""
    code = str(value or "").strip().lower().replace("_", "-").split("-")[0]
    return code if code in LABELS else DEFAULT_LANGUAGE


def is_rtl(language: Any) -> bool:
    return normalize_language(language) in RTL_LANGUAGES


def contains_rtl(text: Any) -> bool:
    return bool(_RTL_CHARS.search(str(text or "")))


# ---------------------------------------------------------------------------
# Fonts
# ---------------------------------------------------------------------------
_font_lock = threading.Lock()
_arabic_fonts_ready: Optional[bool] = None


def register_rtl_fonts() -> bool:
    """Registers the bundled Arabic family once per process.

    Returns ``False`` (and logs) when the font files are missing so callers can
    degrade to Helvetica instead of failing the download outright.
    """
    global _arabic_fonts_ready

    with _font_lock:
        if _arabic_fonts_ready is not None:
            return _arabic_fonts_ready

        try:
            from reportlab.pdfbase import pdfmetrics
            from reportlab.pdfbase.ttfonts import TTFont

            for font_name, filename in ARABIC_FONT_FILES:
                path = FONT_DIR / filename
                if not path.is_file():
                    raise FileNotFoundError(path)
                pdfmetrics.registerFont(TTFont(font_name, str(path)))

            pdfmetrics.registerFontFamily(
                "MizaanArabic",
                normal="MizaanArabic",
                bold="MizaanArabic-Bold",
                # The family has no italic; reusing the upright faces keeps
                # <i> markup renderable instead of raising.
                italic="MizaanArabic",
                boldItalic="MizaanArabic-Bold",
            )
            _arabic_fonts_ready = True
        except Exception:
            logger.exception(
                "Arabic font registration failed - falling back to Helvetica, "
                "which cannot render Arabic glyphs."
            )
            _arabic_fonts_ready = False

        return _arabic_fonts_ready


# ---------------------------------------------------------------------------
# Shaping / bidi
# ---------------------------------------------------------------------------
_shaper_lock = threading.Lock()
_shaper: Optional[Tuple[Any, Any]] = None
_shaper_loaded = False


def _load_shaper() -> Optional[Tuple[Any, Any]]:
    global _shaper, _shaper_loaded

    with _shaper_lock:
        if _shaper_loaded:
            return _shaper
        _shaper_loaded = True
        try:
            import arabic_reshaper
            from bidi.algorithm import get_display

            _shaper = (arabic_reshaper.reshape, get_display)
        except Exception:
            logger.exception(
                "arabic-reshaper/python-bidi unavailable - Arabic will render "
                "unshaped and in logical order."
            )
            _shaper = None
        return _shaper


def shape_rtl(text: Any) -> str:
    """Returns one line of RTL text in display order.

    Must be applied per line: the bidirectional algorithm is defined on a
    single line of text, so shaping a whole paragraph and wrapping afterwards
    reverses the reading order of every line but the first.
    """
    value = "" if text is None else str(text)
    if not value or not contains_rtl(value):
        return value

    shaper = _load_shaper()
    if shaper is None:
        return value

    reshape, get_display = shaper
    try:
        return get_display(reshape(value), base_dir="R")
    except Exception:
        logger.exception("Failed to shape RTL text")
        return value


def wrap_rtl_lines(
    text: Any, font_name: str, font_size: float, max_width: float
) -> List[str]:
    """Greedy word wrap in logical order, returning shaped display lines."""
    value = "" if text is None else str(text)
    if not value.strip():
        return []

    limit = max(float(max_width), 1.0)
    lines: List[str] = []

    for block in value.splitlines():
        words = block.split()
        if not words:
            lines.append("")
            continue

        current = ""
        for word in words:
            candidate = word if not current else f"{current} {word}"
            width = stringWidth(shape_rtl(candidate), font_name, font_size)
            if width <= limit or not current:
                current = candidate
            else:
                lines.append(current)
                current = word
        if current:
            lines.append(current)

    return [shape_rtl(line) for line in lines]


def escape_xml(value: Any) -> str:
    """Report text is model-generated, so markup characters are neutralised."""
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .strip()
    )


class RtlParagraph(Paragraph):
    """A paragraph that wraps logically and renders in visual order.

    ReportLab wraps text itself, which is incompatible with reordering the
    bidirectional text up front. This flowable therefore performs its own line
    breaking at the width it is handed, shapes each line, and hands ReportLab
    pre-broken lines that need no further reflow.
    """

    def __init__(self, text: Any, style: ParagraphStyle):
        self._logical_text = "" if text is None else str(text).strip()
        self._rtl_style = style
        self._built_width: Optional[float] = None
        super().__init__(escape_xml(self._logical_text) or "&nbsp;", style)

    def _rebuild(self, available_width: float) -> None:
        lines = wrap_rtl_lines(
            self._logical_text,
            self._rtl_style.fontName,
            self._rtl_style.fontSize,
            available_width,
        )
        markup = "<br/>".join(escape_xml(line) for line in lines) or "&nbsp;"
        Paragraph.__init__(self, markup, self._rtl_style)
        self._built_width = available_width

    def wrap(self, availWidth, availHeight):  # noqa: N803 - ReportLab API
        if self._built_width is None or abs(availWidth - self._built_width) > 0.5:
            self._rebuild(availWidth)
        return Paragraph.wrap(self, availWidth, availHeight)


# ---------------------------------------------------------------------------
# Localizer
# ---------------------------------------------------------------------------
class Localizer:
    """Every language-dependent decision the renderer needs, in one object."""

    def __init__(self, language: Any = DEFAULT_LANGUAGE):
        self.language = normalize_language(language)
        self.is_rtl = self.language in RTL_LANGUAGES

        if self.is_rtl and register_rtl_fonts():
            self.font = "MizaanArabic"
            self.font_bold = "MizaanArabic-Bold"
            self.font_italic = "MizaanArabic"
        else:
            self.font, self.font_bold, self.font_italic = LATIN_FONTS

        self.alignment = TA_RIGHT if self.is_rtl else TA_LEFT

    # -- text lookup --------------------------------------------------------
    def text(self, key: str, **params: Any) -> str:
        catalog = LABELS.get(self.language, LABELS[DEFAULT_LANGUAGE])
        template = catalog.get(key) or LABELS[DEFAULT_LANGUAGE].get(key, "")
        if params:
            try:
                return template.format(**params)
            except (KeyError, IndexError):
                return template
        return template

    def _lookup(self, table: Dict[str, Dict[str, str]], key: Any,
                default: str = "") -> str:
        entry = str(key or "").strip()
        catalog = table.get(self.language, table[DEFAULT_LANGUAGE])
        return catalog.get(entry) or table[DEFAULT_LANGUAGE].get(entry, default or entry)

    def section_icon(self, key: str) -> str:
        icons = SECTION_ICONS.get(self.language, SECTION_ICONS[DEFAULT_LANGUAGE])
        return icons.get(key, SECTION_ICONS[DEFAULT_LANGUAGE].get(key, ""))

    def risk_band(self, key: Any) -> str:
        return self._lookup(RISK_BAND_LABELS, key)

    def status(self, key: Any) -> str:
        return self._lookup(STATUS_LABELS, key, self.text("empty_verdict"))

    def priority(self, key: Any) -> str:
        return self._lookup(PRIORITY_LABELS, key)

    def risk_level(self, key: Any) -> str:
        return self._lookup(RISK_LEVEL_LABELS, key)

    def classification(self, value: Any) -> str:
        """Translates the derived English labels, passes model text through."""
        return self._lookup(CLASSIFICATION_LABELS, value, str(value or ""))

    def audit_type(self, value: Any) -> str:
        return self._lookup(AUDIT_TYPE_LABELS, value, str(value or ""))

    def confidentiality_notice(self, configured: Optional[str] = None) -> str:
        # The English notice stays operator-configurable; translations are
        # only used when the operator has not overridden it.
        if self.language == DEFAULT_LANGUAGE and configured:
            return configured
        return self.text("confidentiality_notice")

    def format_date(self, moment: datetime) -> str:
        months = MONTHS.get(self.language, MONTHS[DEFAULT_LANGUAGE])
        return f"{moment.day:02d} {months[moment.month - 1]} {moment.year}"

    # -- rendering helpers --------------------------------------------------
    def shape(self, text: Any) -> str:
        """Prepares a single line for direct canvas drawing."""
        value = "" if text is None else str(text)
        return shape_rtl(value) if self.is_rtl else value

    def paragraph(self, text: Any, style: ParagraphStyle) -> Paragraph:
        if self.is_rtl:
            return RtlParagraph(text, style)
        return Paragraph(escape_xml(text), style)


_ENGLISH = Localizer(DEFAULT_LANGUAGE)
_current: ContextVar[Localizer] = ContextVar("mizaan_report_localizer")


def current_localizer() -> Localizer:
    """The localizer for the report being rendered on this thread/task."""
    return _current.get(_ENGLISH)


def use_language(language: Any) -> Tuple[Localizer, Any]:
    """Activates a language for the current context.

    Returns the localizer and the token needed to restore the previous value,
    so concurrent renders in different languages cannot leak into each other.
    """
    localizer = Localizer(language)
    return localizer, _current.set(localizer)


def reset_language(token: Any) -> None:
    try:
        _current.reset(token)
    except (ValueError, LookupError):  # pragma: no cover - defensive
        pass
